name: ${project.name}
description: ${project.description}
main: com.starmediadev.plugins.starmcutils.StarMCUtils
version: ${project.version}
api-version: 1.18
softdepend: [StarData]
libraries:
  - com.google.code.gson:gson:2.8.7
commands:
  addcolor: 